### ISSUE TITLE
Saving an AL file causes empty lines to be removed

### ISSUE THREAD

**Issue by daansaveyn** [anzwdev/az-al-dev-tools-server#39]
Hi,

After inserting an empty line using the enter key and saving the file, the empty line is removed again.

![Issue Empty Lines](https://user-images.githubusercontent.com/48217797/118490210-fce91380-b71d-11eb-8e7e-8e49b3d2fc1f.gif)

I believe this has something to do with the removal of unnecessary space characters. Existing empty lines are unaffected.

Existing empty line:

![image](https://user-images.githubusercontent.com/48217797/118489847-98c64f80-b71d-11eb-80a2-27d8dec64e41.png)

Empty line created using the enter key:

![image](https://user-images.githubusercontent.com/48217797/118489994-c14e4980-b71d-11eb-9504-174cdd41f406.png)

**Comment by anzwdev** [comment]
Hi

Thank you for reporting this problem. I know about it and I am trying to find a solution. It has been reported as part of this issue:
https://github.com/anzwdev/al-code-outline/issues/213

**Comment by anzwdev** [comment]
I've fixed the issue and released a new version of the extension
